name: CI (bors)

on:
  push:
    branches:
      - '**'

jobs:
  docker_linux_tier2:
    name: Docker Linux Tier2
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 12
      matrix:
        target: [
          # FIXME: Mysterious failures in CI, see
          # https://github.com/rust-lang/libc/issues/2081
          # aarch64-linux-android,
          
          #aarch64-unknown-linux-gnu,
          #aarch64-unknown-linux-musl,
          #arm-linux-androideabi,
          #arm-unknown-linux-gnueabihf,
          #arm-unknown-linux-musleabihf,
          #asmjs-unknown-emscripten,
          #i686-linux-android,
          i686-unknown-linux-musl,
          #mips-unknown-linux-gnu,
          #mips-unknown-linux-musl,
          # FIXME: Somehow failed on CI
          # https://github.com/rust-lang/libc/runs/1659882216
          # mips64-unknown-linux-gnuabi64,
          # mips64el-unknown-linux-gnuabi64,
          
          #mipsel-unknown-linux-musl,
          #powerpc-unknown-linux-gnu,
          #powerpc64-unknown-linux-gnu,
          #powerpc64le-unknown-linux-gnu,
          #s390x-unknown-linux-gnu,
          #riscv64gc-unknown-linux-gnu,
          
          # FIXME: A recent nightly causes a linker failure:
          # https://github.com/rust-lang/rust/issues/76679
          # See this comment for more details:
          # https://github.com/rust-lang/libc/pull/2225#issuecomment-880696737
          #wasm32-wasi,
          
          #sparc64-unknown-linux-gnu,
          #wasm32-unknown-emscripten,
          #x86_64-linux-android,
          #x86_64-unknown-linux-gnux32,
          #x86_64-unknown-linux-musl,
          # FIXME: It seems some items in `src/unix/mod.rs`
          # aren't defined on redox actually.
          # x86_64-unknown-redox,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: TARGET=${{ matrix.target }} sh ./ci/install-rust.sh
      - name: Execute run-docker.sh
        run: LIBC_CI=1 sh ./ci/run-docker.sh ${{ matrix.target }}

  build_channels_linux:
    name: Build Channels Linux
    needs: docker_linux_tier2
    runs-on: ubuntu-20.04
    env:
      OS: linux
    strategy:
      max-parallel: 5
      matrix:
        toolchain: [
          stable,
          beta,
          nightly,
          1.13.0,
          1.19.0,
          1.24.0,
          1.25.0,
          1.30.0,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/install-rust.sh
      - name: Execute build.sh
        run: LIBC_CI=1 TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/build.sh

  docs:
    name: Generate documentation
    runs-on: ubuntu-20.04
    needs: docker_linux_tier2
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: sh ./ci/install-rust.sh
      - name: Generate documentation
        run: LIBC_CI=1 sh ci/dox.sh
